Problem - 1: Array Creation:
1. Initialize an empty array with size 2X2.

---




In [ ]:
import numpy as np

# Create an empty 2x2 array
array = np.empty((2, 2))
print(array)


[[4.92172642e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

# Create a 4x2 array filled with ones
array_ones = np.ones((4, 2))
print(array_ones)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

# Create an array with shape (3, 3), filled with the value 7
array_filled = np.full((3, 3), 7)
print(array_filled)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

# Given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a new array of zeros with the same shape and type as given_array
zeros_array = np.zeros_like(given_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np

# Given array
given_array = np.array([[4, 5, 6], [7, 8, 9]])

# Create a new array of ones with the same shape and type as given_array
ones_array = np.ones_like(given_array)
print(ones_array)


[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
np_array = np.array(new_list)

print(np_array)


[1 2 3 4]


 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

# Create an array with values ranging from 10 to 49
array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np

# Create an array with values from 0 to 8
array = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np

# Create a random array of size 30
random_array = np.random.random(30)

# Calculate the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)


Random Array: [0.24284563 0.18568436 0.18074822 0.23103661 0.98936426 0.6900776
 0.98079017 0.34593082 0.00175709 0.39753578 0.33059024 0.38544969
 0.18504064 0.9923117  0.8566553  0.67181546 0.28751294 0.33507134
 0.66043914 0.1540345  0.04271221 0.62588261 0.39256643 0.80950198
 0.80631367 0.26080376 0.47884603 0.50783171 0.82764021 0.90500034]
Mean of the Array: 0.4920596808590882


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

Random 10x10 Array:
[[0.34613582 0.30787959 0.90110564 0.63332791 0.06289347 0.77966726
  0.50755431 0.88727714 0.93663703 0.54611129]
 [0.83720965 0.38190788 0.5958964  0.13161649 0.17106795 0.94262851
  0.6647542  0.19154594 0.85939148 0.20471482]
 [0.04827697 0.22047573 0.49232043 0.91595266 0.09790513 0.60600001
  0.38244337 0.04724865 0.75941394 0.7646571 ]
 [0.31575463 0.62742221 0.22698453 0.66047413 0.02144176 0.91391903
  0.06380165 0.34644659 0.33213218 0.81352827]
 [0.15934604 0.32714799 0.40146505 0.13095652 0.43515161 0.71279967
  0.2113717  0.45374583 0.56611431 0.67120783]
 [0.58629156 0.03732596 0.83849759 0.9726862  0.93298522 0.36608751
  0.92901184 0.86030048 0.47563584 0.63131928]
 [0.65156667 0.63300866 0.84658742 0.4283524  0.92674915 0.11483506
  0.60104105 0.55130214 0.16315275 0.16614863]
 [0.51480177 0.46894837 0.53571364 0.18008254 0.98671655 0.08527049
  0.92735874 0.11018901 0.67550084 0.02959121]
 [0.19138461 0.37954885 0.79454267 0.50845194 0.96892917 0.8

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
# Given array
arr = [1, 2, 0, 0, 4, 0]

# Reverse the array using slicing
reversed_arr = arr[::-1]

print(reversed_arr)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

# Define the size of the array (e.g., 5x5)
size = 5

# Create a 2D array filled with zeros
array = np.zeros((size, size), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Set top row to 1
array[-1, :] = 1  # Set bottom row to 1
array[:, 0] = 1  # Set left column to 1
array[:, -1] = 1  # Set right column to 1

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# Create an 8x8 matrix filled with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with 1s
checkerboard[1::2, ::2] = 1  # Set 1s in the alternating columns for even rows
checkerboard[::2, 1::2] = 1  # Set 1s in the alternating columns for odd rows

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Add the two arrays
result = x + y

print(result)


[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Subtract the two arrays
result = x - y

print(result)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Multiply the array x by an integer (for example, 2)
result_x = x * 2

# Multiply the array y by an integer (for example, 3)
result_y = y * 3

print("x multiplied by 2:")
print(result_x)

print("\ny multiplied by 3:")
print(result_y)


x multiplied by 2:
[[ 2  4]
 [ 6 10]]

y multiplied by 3:
[[15 18]
 [21 24]]


4. Find the square of each element of the array.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Square each element of the array x
square_x = x ** 2

# Alternatively, you can use np.square() to square each element
square_y = np.square(y)

print("Square of each element in x:")
print(square_x)

print("\nSquare of each element in y:")
print(square_y)


Square of each element in x:
[[ 1  4]
 [ 9 25]]

Square of each element in y:
[[25 36]
 [49 64]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])  # 2x2 array
y = np.array([[5, 6], [7, 8]])  # 2x2 array
v = np.array([9, 10])           # 1D array
w = np.array([11, 12])          # 1D array

# Dot product of v and w (1D arrays)
dot_v_w = np.dot(v, w)

# Dot product of x and v (2D array x and 1D array v)
dot_x_v = np.dot(x, v)

# Dot product of x and y (2D array x and 2D array y)
dot_x_y = np.dot(x, y)

# Print the results
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])  # 2x2 array
y = np.array([[5, 6], [7, 8]])  # 2x2 array
v = np.array([9, 10])           # 1D array
w = np.array([11, 12])          # 1D array

# Concatenate x and y along rows (axis=0)
concat_x_y = np.concatenate((x, y), axis=0)  # Or you can use np.vstack((x, y))

# Concatenate v and w along columns (axis=1)
# Reshape v and w from 1D to 2D before concatenating
v_reshaped = v.reshape(-1, 1)  # Convert v to a 2D column vector
w_reshaped = w.reshape(-1, 1)  # Convert w to a 2D column vector
concat_v_w = np.concatenate((v_reshaped, w_reshaped), axis=1)  # Or use np.hstack((v_reshaped, w_reshaped))

# Print the results
print("Concatenated x and y along rows:")
print(concat_x_y)

print("\nConcatenated v and w along columns:")
print(concat_v_w)


Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

# Attempt to concatenate x and v
concatenated_result = np.concatenate((x, v))  # This line causes an error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

We will get a ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Reasoning:
np.concatenate requires arrays to have compatible shapes along the concatenation axis.
x is a 2D array with shape (2, 2).
v is a 1D array with shape (2,).
The dimensions along the concatenation axis (default axis=0) don't match. x has 2 rows, and v has an implied 1 row (as a 1D array).

Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)
identity_matrix = np.eye(2)  # Create a 2x2 identity matrix

print(np.allclose(result, identity_matrix))  # Output: True if approximately equal

True


2. Prove AB ̸= BA.

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print(np.array_equal(AB, BA))  # Output: False if not equal


False


3. Prove (AB)ᵀ = BᵀAᵀ

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Calculate
AB_transpose = np.dot(A, B).transpose()

# Calculate BᵀAᵀ
B_transpose_A_transpose = np.dot(B.transpose(), A.transpose())

print(np.array_equal(AB_transpose, B_transpose_A_transpose))  # Output: True if equal

True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant matrix B
B = np.array([[-1],
              [-3],
              [9]])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution:")
print(X)

Solution:
[[ 2.]
 [ 1.]
 [-2.]]


4.2 Experiment: How Fast is Numpy?

Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise addition using a loop
result = [list1[i] + list2[i] for i in range(len(list1))]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise addition: {end_time - start_time} seconds")

Time taken for element-wise addition: 0.18393349647521973 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise addition using NumPy arrays
result = array1 + array2  # NumPy allows direct element-wise addition

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise addition using NumPy: {end_time - start_time} seconds")

Time taken for element-wise addition using NumPy: 0.004674434661865234 seconds


Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise multiplication using a loop
result = [list1[i] * list2[i] for i in range(len(list1))]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")

Time taken for element-wise multiplication using Python lists: 0.19485783576965332 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform element-wise multiplication using NumPy arrays
result = array1 * array2  # NumPy allows direct element-wise multiplication

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for element-wise multiplication using NumPy: {end_time - start_time} seconds")

Time taken for element-wise multiplication using NumPy: 0.006338596343994141 seconds


Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1, 1000001)]  # List with values from 1 to 1,000,000
list2 = [i for i in range(1000001, 2000001)]  # List with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform dot product using a loop (element-wise multiplication and sum)
dot_product = sum(list1[i] * list2[i] for i in range(len(list1)))

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")


Time taken for dot product using Python lists: 0.14129972457885742 seconds


Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of size 1,000,000
array1 = np.arange(1, 1000001)  # Array with values from 1 to 1,000,000
array2 = np.arange(1000001, 2000001)  # Array with values from 1,000,001 to 2,000,000

# Start measuring time
start_time = time.time()

# Perform dot product using NumPy arrays
dot_product = np.dot(array1, array2)

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for dot product using NumPy: {end_time - start_time} seconds")

Time taken for dot product using NumPy: 0.002712726593017578 seconds


Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

In [ ]:
import time

# Create two 1000x1000 matrices
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]  # 1000x1000 matrix
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]  # 1000x1000 matrix

# Start measuring time
start_time = time.time()

# Perform matrix multiplication (result = matrix1 * matrix2)
result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time} seconds")


Time taken for matrix multiplication using Python lists: 257.76068210601807 seconds


Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Create two 1000x1000 matrices with random values
matrix1 = np.random.rand(1000, 1000)  # 1000x1000 matrix with random values
matrix2 = np.random.rand(1000, 1000)  # 1000x1000 matrix with random values

# Start measuring time
start_time = time.time()

# Perform matrix multiplication using NumPy
result = np.dot(matrix1, matrix2)  # You can also use matrix1 @ matrix2

# Measure the time taken
end_time = time.time()

# Print the time taken for the operation
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time} seconds")


Time taken for matrix multiplication using NumPy: 0.13790535926818848 seconds
